export const COUNTRY_NAMES: Record<string, string> = {
    FR: "France",
    DE: "Allemagne",
    IT: "Italie",
    ES: "Espagne",
    BE: "Belgique",
    SI: "Slovénie",
    RS: "Serbie",
    HR: "Croatie",
    PT: "Portugal",
    GR: "Grèce",
    NL: "Pays-Bas",
    AT: "Autriche",
    PL: "Pologne",
    CZ: "Tchéquie",
    SK: "Slovaquie",
    HU: "Hongrie",
    RO: "Roumanie",
    BG: "Bulgarie",
    CH: "Suisse",
    GB: "Royaume-Uni",
    LU: "Luxembourg",
};
