"""add_pricing_type_to_partner_quote

Revision ID: 38a0786708da
Revises: fa228c67a366
Create Date: 2026-01-29 10:28:19.016814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a0786708da'
down_revision: Union[str, None] = 'fa228c67a366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_quotes', sa.Column('pricing_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_quotes', 'pricing_type')
    # ### end Alembic commands ###
