"""Add User model and enhance CustomerQuote

Revision ID: 5ec4c3702320
Revises: e4a7f2c31d85
Create Date: 2026-02-10 11:35:39.856569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec4c3702320'
down_revision: Union[str, None] = 'e4a7f2c31d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('customer_quotes', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('customer_quotes', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'customer_quotes', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'customer_quotes', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_quotes', type_='foreignkey')
    op.drop_constraint(None, 'customer_quotes', type_='foreignkey')
    op.drop_column('customer_quotes', 'updated_by')
    op.drop_column('customer_quotes', 'created_by')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
