"""initial

Revision ID: c78cb004e971
Revises: 
Create Date: 2026-01-24 18:33:44.045269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c78cb004e971'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_prisma_migrations')
    op.alter_column('customers', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customers', 'company',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customers', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True)
    op.drop_index('customers_email_key', table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.add_column('generated_quotes', sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('generated_quotes', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('generated_quotes', 'quote_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('generated_quotes', 'customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('generated_quotes', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING', 'SENT', 'VIEWED', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='QuoteStatus'),
               nullable=True,
               existing_server_default=sa.text('\'DRAFT\'::"QuoteStatus"'))
    op.alter_column('generated_quotes', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('generated_quotes', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'EUR'::text"))
    op.alter_column('generated_quotes', 'pdf_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('generated_quotes', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('generated_quotes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True)
    op.drop_index('generated_quotes_customer_id_idx', table_name='generated_quotes')
    op.drop_index('generated_quotes_quote_number_key', table_name='generated_quotes')
    op.drop_index('generated_quotes_status_idx', table_name='generated_quotes')
    op.create_index('ix_generated_quotes_customer_id', 'generated_quotes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_generated_quotes_quote_number'), 'generated_quotes', ['quote_number'], unique=True)
    op.create_index('ix_generated_quotes_status', 'generated_quotes', ['status'], unique=False)
    op.drop_constraint('generated_quotes_customer_id_fkey', 'generated_quotes', type_='foreignkey')
    op.create_foreign_key(None, 'generated_quotes', 'customers', ['customer_id'], ['id'])
    op.drop_column('generated_quotes', 'metadata')
    op.alter_column('import_jobs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('import_jobs', 'partner_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('import_jobs', 'filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('import_jobs', 'file_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('import_jobs', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ImportStatus'),
               nullable=True,
               existing_server_default=sa.text('\'PENDING\'::"ImportStatus"'))
    op.alter_column('import_jobs', 'total_rows',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('import_jobs_partner_id_fkey', 'import_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'import_jobs', 'partners', ['partner_id'], ['id'])
    op.add_column('partner_quotes', sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('partner_quotes', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'partner_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'origin_postal_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('partner_quotes', 'origin_city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'origin_country',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'dest_postal_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('partner_quotes', 'dest_city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'dest_country',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'EUR'::text"))
    op.alter_column('partner_quotes', 'delivery_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('partner_quotes', 'valid_from',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('partner_quotes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('partner_quotes', 'import_job_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('partner_quotes', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('partner_quotes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True)
    op.drop_index('partner_quotes_is_active_valid_until_idx', table_name='partner_quotes')
    op.drop_index('partner_quotes_origin_country_dest_country_idx', table_name='partner_quotes')
    op.drop_index('partner_quotes_transport_mode_idx', table_name='partner_quotes')
    op.create_index('ix_partner_quotes_active_valid', 'partner_quotes', ['is_active', 'valid_until'], unique=False)
    op.create_index('ix_partner_quotes_origin_dest', 'partner_quotes', ['origin_country', 'dest_country'], unique=False)
    op.create_index('ix_partner_quotes_transport_mode', 'partner_quotes', ['transport_mode'], unique=False)
    op.drop_constraint('partner_quotes_import_job_id_fkey', 'partner_quotes', type_='foreignkey')
    op.drop_constraint('partner_quotes_partner_id_fkey', 'partner_quotes', type_='foreignkey')
    op.create_foreign_key(None, 'partner_quotes', 'partners', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'partner_quotes', 'import_jobs', ['import_job_id'], ['id'])
    op.drop_column('partner_quotes', 'metadata')
    op.alter_column('partners', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partners', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partners', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partners', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('partners', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('partners', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('partners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True)
    op.drop_index('partners_code_key', table_name='partners')
    op.create_index(op.f('ix_partners_code'), 'partners', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partners_code'), table_name='partners')
    op.create_index('partners_code_key', 'partners', ['code'], unique=True)
    op.alter_column('partners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False)
    op.alter_column('partners', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('partners', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('partners', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('partners', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('partners', 'code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('partners', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('partner_quotes', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'partner_quotes', type_='foreignkey')
    op.drop_constraint(None, 'partner_quotes', type_='foreignkey')
    op.create_foreign_key('partner_quotes_partner_id_fkey', 'partner_quotes', 'partners', ['partner_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('partner_quotes_import_job_id_fkey', 'partner_quotes', 'import_jobs', ['import_job_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index('ix_partner_quotes_transport_mode', table_name='partner_quotes')
    op.drop_index('ix_partner_quotes_origin_dest', table_name='partner_quotes')
    op.drop_index('ix_partner_quotes_active_valid', table_name='partner_quotes')
    op.create_index('partner_quotes_transport_mode_idx', 'partner_quotes', ['transport_mode'], unique=False)
    op.create_index('partner_quotes_origin_country_dest_country_idx', 'partner_quotes', ['origin_country', 'dest_country'], unique=False)
    op.create_index('partner_quotes_is_active_valid_until_idx', 'partner_quotes', ['is_active', 'valid_until'], unique=False)
    op.alter_column('partner_quotes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False)
    op.alter_column('partner_quotes', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('partner_quotes', 'import_job_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('partner_quotes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('partner_quotes', 'valid_from',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('partner_quotes', 'delivery_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('partner_quotes', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'EUR'::text"))
    op.alter_column('partner_quotes', 'dest_country',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'dest_city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'dest_postal_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('partner_quotes', 'origin_country',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'origin_city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'origin_postal_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('partner_quotes', 'partner_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('partner_quotes', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('partner_quotes', 'meta_data')
    op.drop_constraint(None, 'import_jobs', type_='foreignkey')
    op.create_foreign_key('import_jobs_partner_id_fkey', 'import_jobs', 'partners', ['partner_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('import_jobs', 'errors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('import_jobs', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'total_rows',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ImportStatus'),
               nullable=False,
               existing_server_default=sa.text('\'PENDING\'::"ImportStatus"'))
    op.alter_column('import_jobs', 'file_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('import_jobs', 'filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('import_jobs', 'partner_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('import_jobs', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('generated_quotes', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generated_quotes', type_='foreignkey')
    op.create_foreign_key('generated_quotes_customer_id_fkey', 'generated_quotes', 'customers', ['customer_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index('ix_generated_quotes_status', table_name='generated_quotes')
    op.drop_index(op.f('ix_generated_quotes_quote_number'), table_name='generated_quotes')
    op.drop_index('ix_generated_quotes_customer_id', table_name='generated_quotes')
    op.create_index('generated_quotes_status_idx', 'generated_quotes', ['status'], unique=False)
    op.create_index('generated_quotes_quote_number_key', 'generated_quotes', ['quote_number'], unique=True)
    op.create_index('generated_quotes_customer_id_idx', 'generated_quotes', ['customer_id'], unique=False)
    op.alter_column('generated_quotes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False)
    op.alter_column('generated_quotes', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('generated_quotes', 'pdf_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generated_quotes', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'EUR'::text"))
    op.alter_column('generated_quotes', 'items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('generated_quotes', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING', 'SENT', 'VIEWED', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='QuoteStatus'),
               nullable=False,
               existing_server_default=sa.text('\'DRAFT\'::"QuoteStatus"'))
    op.alter_column('generated_quotes', 'customer_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('generated_quotes', 'quote_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('generated_quotes', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('generated_quotes', 'meta_data')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index('customers_email_key', 'customers', ['email'], unique=True)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customers', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customers', 'first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customers', 'company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customers', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='_prisma_migrations_pkey')
    )
    # ### end Alembic commands ###
