"""add_customer_quotes_and_partner_margin

Revision ID: fa228c67a366
Revises: c78cb004e971
Create Date: 2026-01-27 12:10:51.023982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa228c67a366'
down_revision: Union[str, None] = 'c78cb004e971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='customerquotestatus'), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_company', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('transport_subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fees_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_margin', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_quotes_id'), 'customer_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_customer_quotes_reference'), 'customer_quotes', ['reference'], unique=True)
    op.create_index(op.f('ix_customer_quotes_status'), 'customer_quotes', ['status'], unique=False)
    op.create_table('customer_quote_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quote_id', sa.String(), nullable=True),
    sa.Column('item_type', sa.Enum('TRANSPORT', 'FEE', name='customerquoteitemtype'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('partner_quote_id', sa.String(), nullable=True),
    sa.Column('origin_city', sa.String(), nullable=True),
    sa.Column('origin_country', sa.String(), nullable=True),
    sa.Column('dest_city', sa.String(), nullable=True),
    sa.Column('dest_country', sa.String(), nullable=True),
    sa.Column('partner_name', sa.String(), nullable=True),
    sa.Column('transport_mode', sa.String(), nullable=True),
    sa.Column('delivery_time', sa.String(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('margin_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_quote_id'], ['partner_quotes.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['customer_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_quote_items_id'), 'customer_quote_items', ['id'], unique=False)
    op.create_index(op.f('ix_customer_quote_items_quote_id'), 'customer_quote_items', ['quote_id'], unique=False)
    op.add_column('partners', sa.Column('default_margin', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'default_margin')
    op.drop_index(op.f('ix_customer_quote_items_quote_id'), table_name='customer_quote_items')
    op.drop_index(op.f('ix_customer_quote_items_id'), table_name='customer_quote_items')
    op.drop_table('customer_quote_items')
    op.drop_index(op.f('ix_customer_quotes_status'), table_name='customer_quotes')
    op.drop_index(op.f('ix_customer_quotes_reference'), table_name='customer_quotes')
    op.drop_index(op.f('ix_customer_quotes_id'), table_name='customer_quotes')
    op.drop_table('customer_quotes')
    # ### end Alembic commands ###
